language: generic

sudo: required
services:
  - docker

# Running tests, provide Dockerfile.dev as the docker file
before_install:
  #- docker buid -t react-test-image -f ./client/Dockerfile.dev ./client
  - docker build -t react-test-image -f ./client/Dockerfile.dev ./client

# Any command returning non-zero will be considered fail
script:
  - docker run -e CI=true react-test-image npm test


# Default Dockerfile
after_success:
    - docker build -t docker-client ./client
    - docker build -t docker-nginx ./nginx
    - docker build -t docker-server ./server
    - docker build -t docker-worker ./worker 
    # Login to docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # push to docker hub
    - docker push docker-client
    - docker push docker-nginx
    - docker push docker-server
    - docker push docker-worker
