language: generic

sudo: required
services:
  - docker

# Running tests, provide Dockerfile.dev as the docker file
before_install:
  #- docker buid -t react-test-image -f ./client/Dockerfile.dev ./client
  - docker build -t ejblitz/react-test-image -f ./client/Dockerfile.dev ./client

# Any command returning non-zero will be considered fail
script:
  - docker run -e CI=true ejblitz/react-test-image npm test


# Default Dockerfile
after_success:
    - docker build -t ejblitz/docker-client ./client
    - docker build -t ejblitz/docker-nginx ./nginx
    - docker build -t ejblitz/docker-server ./server
    - docker build -t ejblitz/docker-worker ./worker 
    # Login to docker cli
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
    # push to docker hub
    - docker push ejblitz/docker-client
    - docker push ejblitz/docker-nginx
    - docker push ejblitz/docker-server
    - docker push ejblitz/docker-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: fibonacci-docker
  env: FibonacciDocker-env
  bucket_name: elasticbeanstalk-us-east-2-244522864296
  bucket_path: fibonacci-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_key_id: 
    secure: $AWS_SECRET_KEY

